image: docker:20.10
services:
  - docker:20.10-dind

stages:
  - build

build-testing:
  stage: build
  except:
    - release-4.4
    - release-4.5
    - release-4.6
  tags:
    - docker
  variables:
    DOCKER_BUILDKIT: 1
    CRYOSPARC_VERSION: 4.5.1
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION} -t ${IMAGE_TAG} -t ${CI_REGISTRY_IMAGE}:latest --progress=plain --secret id=CRYOSPARC_LICENSE_ID --build-arg="CRYOSPARC_VERSION=${CRYOSPARC_VERSION}" .

build-release-4.4:
  stage: build
  only:
    - release-4.4
  tags:
    - docker
  variables:
    DOCKER_BUILDKIT: 1
    CRYOSPARC_VERSION: 4.4.1
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION} -t ${IMAGE_TAG} -t ${CI_REGISTRY_IMAGE}:latest --progress=plain --secret id=CRYOSPARC_LICENSE_ID --build-arg="CRYOSPARC_VERSION=${CRYOSPARC_VERSION}" .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION}

build-release-4.5:
  stage: build
  only:
    - release-4.5
  tags:
    - docker
  variables:
    DOCKER_BUILDKIT: 1
    CRYOSPARC_VERSION: 4.5.3
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION} -t ${IMAGE_TAG} -t ${CI_REGISTRY_IMAGE}:latest --progress=plain --secret id=CRYOSPARC_LICENSE_ID --build-arg="CRYOSPARC_VERSION=${CRYOSPARC_VERSION}" .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION}

build-release-4.6:
  stage: build
  only:
    - release-4.6
  tags:
    - docker
  variables:
    DOCKER_BUILDKIT: 1
    CRYOSPARC_VERSION: 4.6.2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION} -t ${IMAGE_TAG} -t ${CI_REGISTRY_IMAGE}:latest --progress=plain --secret id=CRYOSPARC_LICENSE_ID --build-arg="CRYOSPARC_VERSION=${CRYOSPARC_VERSION}" .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CRYOSPARC_VERSION}
